### ISSUE TITLE
Smithing autocomplete with no selected recipe crashes the client

### ISSUE THREAD

**Issue by noelle-lavenza** [ApacheTech-VintageStory-Mods/ApacheTech.VintageMods.Knapster#2]
https://github.com/ApacheTech-VintageStory-Mods/ApacheTech.VintageMods.Knapster/blob/4727b8cc3ab3db22722d608feaafba84affaf39e/src/ApacheTech.VintageMods.Knapster/Features/EasySmithing/Patches/EasySmithingUniversalPatches.cs#L110

Recipe is not nullchecked prior to this point. This causes a null reference exception if someone tries autocomplete on a piece of metal on an anvil before a recipe is selected.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ApacheTech.VintageMods.Knapster.Features.EasySmithing.EasySmithing.OnHit(BlockEntityAnvil anvil)
   at ApacheTech.VintageMods.Knapster.Features.EasySmithing.EasySmithing.UniversalPatch_BlockEntityClayForm_OnUseOver_Prefix(BlockEntityAnvil __instance, IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
   at Vintagestory.GameContent.BlockEntityAnvil.OnUseOver_Patch1(BlockEntityAnvil this, IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
```

**Comment by ApacheTech** [comment]
Fixed in 2.0.1. Will be released within the next publish cycle.
